apiVersion: v1
kind: PersistentVolume 
metadata: 
  name: pathnex-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  hostPath: 
    path: /data/pathnex

---

apiVersion: v1
kind: PersistentVolumeClaim 
metadata: 
  name: pathnex-vpc 
spec: 
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi