apiVersion: v1
kind: pod 
metadata:
  name: pathnex-sidecar
spec:
  containers:
    - name: app
      image: nginx 
    - name: log-writer
      image: busybox
      command: ["sh", "-c", "while true; do echo log entry; sleep 5; done"]