stages: 
  - build

variables:
  INSTITUTE_NAME: "Pathnex"

build: 
  stage: build
  image: maven:3.8.1-jdk-17
  script: 
    - git clone https://github.com/Pathnex/sample-java-app.git
    - cd sample-java-app 
    - echo "welcome to $INSTITUTE_NAME devops training"
    - mvn clean package -D institute.name=$INSTITUTE_NAME